'use strict';
const app=document.getElementById('app');
const state={me:null,guilds:[],guild:null,config:null,version:0,meta:null,tab:'overview',dirty:false,staff:[],tickets:[],events:[],member:null,grants:new Set(),busy:false};
const nav=[['overview','◈','Overview'],['security','◆','Antinuke'],['automod','▦','Automod'],['greet','✦','Welcome messages'],['embeds','▤','Message embeds'],['staff','♙','Staff & permissions'],['tickets','▣','Ticket system'],['reactions','◉','Reaction roles'],['audit','☷','Activity log']];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pathGet=p=>p.split('.').reduce((o,k)=>o?.[k],state.config);
const pathSet=(p,v)=>{const keys=p.split('.'),last=keys.pop();keys.reduce((o,k)=>o[k],state.config)[last]=v;state.dirty=true;updateDirty();};
let toastTimer;
function toast(message,error=false){const el=document.getElementById('toast');el.textContent=message;el.className=error?'error':'';el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?11000:6000);}
async function api(path,method='GET',body){const response=await fetch(path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json','X-CSRF-Token':state.me?.csrf||''},...(body!==undefined?{body:JSON.stringify(body)}:{})});const text=await response.text();let data;try{data=JSON.parse(text);}catch{data={error:text};}if(!response.ok){if(response.status===401){state.me=null;renderLogin();}throw new Error(data.error||`Request failed (${response.status})`);}return data;}
const base=()=>`/api/guilds/${state.guild.id}`;
function field(label,path,kind='text',hint=''){const v=pathGet(path);let input=kind==='textarea'?`<textarea data-path="${path}" rows="4">${esc(v)}</textarea>`:`<input type="${kind}" data-path="${path}" value="${esc(v)}" ${kind==='number'?'min="1" max="5"':''}>`;return `<label class="field"><span>${esc(label)}</span>${input}${hint?`<div class="hint">${hint}</div>`:''}</label>`;}
function selectField(label,path,options,multiple=false){const value=pathGet(path);return `<label class="field"><span>${esc(label)}</span><select data-path="${path}" ${multiple?'multiple':''}>${multiple?'':'<option value="">Choose…</option>'}${options.map(o=>`<option value="${esc(o.id)}" ${(multiple?(value||[]).includes(o.id):value===o.id)?'selected':''}>${esc(o.name)}</option>`).join('')}</select>${multiple?'<div class="hint">Choose multiple roles with Ctrl / Command, or your phone’s selector.</div>':''}</label>`;}
const channels=category=>state.meta.channels.filter(c=>c.type===(category?'category':'text'));
const channelField=(label,path,category=false)=>selectField(label,path,channels(category));
const roleField=(label,path,multiple=false)=>selectField(label,path,state.meta.roles,multiple);
const toggle=(label,path)=>`<label class="toggle"><input type="checkbox" data-path="${path}" ${pathGet(path)?'checked':''}>${esc(label)}</label>`;
function channelSelect(id){return `<select id="${id}"><option value="">Choose channel…</option>${channels(false).map(c=>`<option value="${c.id}">#${esc(c.name)}</option>`).join('')}</select>`;}
const badge=(on,yes='Enabled',no='Disabled')=>`<span class="badge ${on?'':'off'}">${on?yes:no}</span>`;
function updateDirty(){const bar=document.getElementById('save-bar');if(bar)bar.hidden=!(state.dirty||state.moduleDirty);const indicator=document.getElementById('saved-indicator');if(indicator)indicator.textContent=(state.dirty||state.moduleDirty)?'Unsaved changes':'All changes saved';}
function renderLogin(){app.innerHTML=`<div class="landing"><header><div class="brand"><span class="brand-symbol">F</span><div>FortuneManager<small>Server management</small></div></div><a class="button" href="https://discord.gg/fortuneleaf">Support ↗</a></header><section class="landing-hero"><div class="eyebrow">FortuneManager</div><h1>Manage your server.</h1><p>Configure security, moderation, roles, welcome messages, and tickets.</p><a class="button primary" href="/auth/login">Continue with Discord →</a><div class="hint">Sign in to see the servers you manage.</div></section><div class="grid3"><div class="card"><div class="eyebrow">01 / People</div><h2>Welcome messages</h2><p>Personal welcomes, embeds, join roles, and reaction roles.</p></div><div class="card"><div class="eyebrow">02 / Team</div><h2>The right permissions</h2><p>Give each staff member exactly the tools they need.</p></div><div class="card"><div class="eyebrow">03 / Support</div><h2>Tickets</h2><p>Private tickets, combined panels, claims, and transcripts.</p></div></div></div>`;}
function renderGuilds(){app.innerHTML=`<div class="landing"><header><div class="brand"><span class="brand-symbol">F</span>FortuneManager</div><button data-action="logout">Sign out</button></header><section class="page-head section-title"><div><div class="eyebrow">Your communities</div><h1>Choose a server</h1><p>Signed in as ${esc(state.me.user.name)}.</p></div></section><div class="guild-grid">${state.guilds.map(g=>`<div class="guild-card">${g.icon?`<img src="${esc(g.icon)}" alt="">`:'<span class="brand-symbol">F</span>'}<h2>${esc(g.name)}</h2>${g.installed?`<button class="primary" data-action="guild" data-id="${g.id}">Open dashboard →</button>`:`<a class="button" href="${esc(state.invite)}&guild_id=${g.id}&disable_guild_select=true" target="_blank" rel="noopener">Add to server ↗</a>`}</div>`).join('')||'<div class="empty">No manageable servers found. You need Manage Server or Administrator permission.</div>'}</div></div>`;}
async function openGuild(id){if((state.dirty||state.moduleDirty)&&!confirm('Discard unsaved changes and switch servers?'))return;const g=state.guilds.find(x=>x.id===id);if(!g)return;const data=await api(`/api/guilds/${id}/config`);state.guild=g;state.meta=data;state.config=data.config;state.version=data.version;state.dirty=false;state.member=null;state.grants=new Set();state.tab='overview';state.moduleDirty=false;await loadTab();renderShell();}
async function loadTab(){if(state.tab==='security')state.security=await api(base()+'/security');if(state.tab==='automod')state.automod=await api(base()+'/automod');if(state.tab==='staff')state.staff=(await api(base()+'/staff')).staff;if(state.tab==='tickets'||state.tab==='overview')state.tickets=(await api(base()+'/tickets')).tickets;if(state.tab==='audit')state.events=(await api(base()+'/audit')).events;}
function renderShell(){const title=nav.find(n=>n[0]===state.tab)[2];app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-symbol">F</span><div>FortuneManager<small>Server dashboard</small></div></div><div class="server-label">WORKSPACE</div><select id="guild-switch" aria-label="Choose server">${state.guilds.filter(g=>g.installed).map(g=>`<option value="${g.id}" ${g.id===state.guild.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select><nav class="nav" aria-label="Dashboard sections">${nav.map(([id,icon,name])=>`<button data-action="tab" data-id="${id}" class="${state.tab===id?'active':''}"><span class="icon">${icon}</span>${name}</button>`).join('')}</nav><div class="sidebar-footer"><span class="status-dot"></span>${state.me.ready?'Bot connected':'Bot connecting'}<br><a href="https://discord.gg/fortuneleaf" target="_blank" rel="noopener">Need a hand? Get support ↗</a><br>.gg/fortuneleaf</div></aside><main class="main"><header class="topbar"><div class="breadcrumb">${esc(state.guild.name)} &nbsp; / &nbsp; <b>${title}</b></div><div class="account"><span id="saved-indicator">${state.dirty?'Unsaved changes':'All changes saved'}</span><span>${esc(state.me.user.name)}</span><button class="small subtle" data-action="logout">Sign out</button></div></header><div class="content" id="content">${renderPage()}</div></main></div><div class="save-bar" id="save-bar" ${state.dirty?'':'hidden'}><span>You have unsaved changes.</span><div class="actions"><button data-action="reset">Discard</button><button class="primary" data-action="save">Save changes</button></div></div>`;renderPreview();}
function head(title,description){return `<section class="page-head"><div><div class="eyebrow">${esc(state.guild.name)}</div><h1>${title}</h1><p>${description}</p></div><div class="actions"><button data-action="refresh">↻ Refresh</button><button class="primary" data-action="save">Save changes</button></div></section>`;}
function renderPage(){return ({security:securityPage,automod:automodPage,overview:overview,greet:greetings,embeds:embedsPage,staff:staffPage,tickets:ticketPage,reactions:reactionsPage,audit:auditPage})[state.tab]();}
function overview(){const c=state.config;return `${head('Server overview','Settings and recent activity.')}<section class="hero"><div class="eyebrow">Server settings</div><h2>FortuneManager</h2><p>Choose a module from the sidebar to configure your server.</p></section><div class="grid3"><div class="stat"><span>Community members</span><div class="number">${Number(state.meta.guild.members||0).toLocaleString()}</div><span>Current member count</span></div><div class="stat"><span>Recent open tickets</span><div class="number">${state.tickets.filter(t=>t.status==='open').length}</div><span>Within the latest 100 tickets</span></div><div class="stat"><span>Command prefix</span><div class="number">${esc(c.prefix)}</div><span>Try ${esc(c.prefix)}help in your server</span></div></div><div class="module-grid">${[['greet','✦','A warm welcome','Personalized greetings, welcome embeds, and automatic join roles.',c.greet.enabled],['staff','♙','A trusted team','Button-selected permissions and a dedicated staff role.',!!c.staff_role_id],['tickets','▣','A place for support','Private conversations with combined panels and saved transcripts.',c.ticket.enabled],['reactions','◉','Let members choose','Give your community roles with a simple reaction.',c.reaction_roles.length>0]].map(([id,icon,title,desc,on])=>`<article class="module"><div class="module-icon">${icon}</div><div><h3>${title}</h3><p>${desc}</p><div class="actions">${badge(on,'Configured','Not configured')}<button class="small subtle" data-action="tab" data-id="${id}">Configure →</button></div></div></article>`).join('')}</div><h2 class="section-title">Server essentials</h2><div class="card"><div class="form-row">${field('Command prefix','prefix','text','The only accepted prefix; 1–8 visible characters.')}${field('Reply cleanup (seconds)','reply_delete_after','number','Default 20. Set 0 to keep replies. Menus last until their timeout.')}${channelField('Moderation log channel','log_channel_id')}</div></div>`;}
function greetings(){return `${head('Welcome messages','Configure messages and roles for new members.')}<div class="grid2"><div><div class="card"><div class="card-head"><div><h2>Welcome messages</h2><p>Greet new members in a channel of your choice.</p></div>${badge(state.config.greet.enabled)}</div>${toggle('Send a message when a member joins','greet.enabled')}${channelField('Welcome channel','greet.channel_id')}${field('Message above the embed','greet.content','textarea')}${toggle('Include a welcome embed','greet.use_embed')}<div class="divider"></div>${field('Embed title','greet.title')}${field('Embed description','greet.description','textarea')}<div class="form-row">${field('Accent color','greet.color','color')}${field('Custom image URL (optional)','greet.image','url')}</div><div class="hint">Variables: <code>{user}</code> <code>{username}</code> <code>{server}</code> <code>{member_count}</code> <code>{user_id}</code></div></div><div class="card"><h2>Join roles</h2><p>Assign roles automatically when a member arrives.</p>${roleField('Roles to assign','greet.autorole_ids',true)}<div class="hint">Administrative, moderation, and staff roles cannot be assigned automatically.</div></div><button data-action="greet-test">Send test welcome</button><div class="hint">Save your changes first. The test is sent to the configured channel.</div></div><div><div class="preview-caption">Message preview · Sample member</div><div id="greet-preview"></div></div></div>`;}
function renderPreview(){renderCustomPreview();const el=document.getElementById('greet-preview');if(!el)return;const c=state.config.greet;const sample=s=>String(s||'').replaceAll('{user}','@wumpus').replaceAll('{username}','wumpus').replaceAll('{server}',state.guild.name).replaceAll('{member_count}',String(state.meta.guild.members||128)).replaceAll('{user_id}','123456789');el.innerHTML=`<div class="preview"><div class="preview-head"><b>FortuneManager</b><small>APP</small></div><div class="preview-content">${esc(sample(c.content))}</div>${c.use_embed?`<div class="discord-embed"><h3>${esc(sample(c.title))}</h3><div class="embed-text">${esc(sample(c.description))}</div>${/^https:\/\//.test(c.image)?`<img class="banner" src="${esc(c.image)}" alt="Configured welcome image">`:''}</div>`:''}</div>`;const e=el.querySelector('.discord-embed');if(e)e.style.borderLeftColor=c.color;}

function embedsPage(){return `${head('Say it with an embed.','Build a branded announcement and send it to your community.')}<div class="grid2"><div class="card"><h2>Message builder</h2><p>Save a reusable draft, then send it when you are ready.</p>${channelField('Destination channel','embeds.channel_id')}${field('Message above the embed','embeds.content','textarea')}${field('Title','embeds.title')}${field('Description','embeds.description','textarea')}<div class="form-row">${field('Accent color','embeds.color','color')}${field('Custom image URL (optional)','embeds.image','url')}</div><div class="divider"></div><div class="card-head"><h2>Embed fields</h2><button class="small" data-action="add-embed-field">＋ Add field</button></div>${state.config.embeds.fields.map((f,i)=>`<div class="row-card">${field('Field name',`embeds.fields.${i}.name`)}${field('Field value',`embeds.fields.${i}.value`,'textarea')}<div class="actions">${toggle('Display inline',`embeds.fields.${i}.inline`)}<button class="small danger right" data-action="remove-embed-field" data-id="${i}">Remove</button></div></div>`).join('')}<div class="hint">Up to 25 fields. A maximum of 5,900 characters across title, description, and fields leaves room for branding.</div><div class="divider"></div><button class="primary" data-action="send-embed">Send embed to Discord ↗</button><div class="hint">Save first. Each send creates a new message. Mentions are disabled.</div></div><div><div class="preview-caption">Embed preview</div><div id="custom-preview"></div></div></div>`;}
function renderCustomPreview(){const el=document.getElementById('custom-preview');if(!el)return;const c=state.config.embeds;el.innerHTML=`<div class="preview"><div class="preview-head"><b>FortuneManager</b><small>APP</small></div><div class="preview-content">${esc(c.content)}</div><div class="discord-embed"><h3>${esc(c.title)}</h3><div class="embed-text">${esc(c.description)}</div>${c.fields.map(f=>`<div class="embed-field"><b>${esc(f.name)}</b><div class="embed-text">${esc(f.value)}</div></div>`).join('')}${/^https:\/\//.test(c.image)?`<img class="banner" src="${esc(c.image)}" alt="Configured embed image">`:''}</div></div>`;el.querySelector('.discord-embed').style.borderLeftColor=c.color;}

function staffPage(){return `${head('A team you can trust.','Assign people, choose permissions, and let your team get to work.')}<div class="grid2"><div><div class="card"><h2>Staff role</h2><p>This role is assigned when you save a staff member.</p>${roleField('Configured staff role','staff_role_id')}<div class="hint">Choose a role without native moderation permissions. The bot checks each member’s saved grants. Place the bot role above this role.</div>${!state.meta.admin?'<div class="notice warn">Only administrators can change staff roles and grants.</div>':''}</div><div class="card"><h2>Member permissions</h2><p>Green permissions are enabled for the selected member.</p><div class="actions"><input id="member-search" placeholder="Search a member or paste their user ID" aria-label="Member search"><button data-action="find-member" ${state.meta.admin?'':'disabled'}>Search</button></div><div id="member-results"></div><div id="staff-editor">${staffEditor()}</div></div></div><div class="card"><div class="card-head"><div><h2>Your staff</h2><p>Permissions are saved separately for this server.</p></div><span class="badge">${state.staff.length} members</span></div>${state.staff.length?state.staff.map(s=>`<div class="row-card"><h3>${esc(s.name)}</h3><div class="hint">${esc(s.user_id)}</div><div>${s.permissions.map(p=>`<span class="pill">${esc(state.meta.permissions[p]||p)}</span>`).join('')||'<span class="hint">No permissions selected</span>'}</div><div class="actions section-title"><button class="small" data-action="edit-staff" data-id="${s.user_id}">Edit permissions</button><button class="small danger" data-action="remove-staff" data-id="${s.user_id}" ${state.meta.admin?'':'disabled'}>Remove</button></div></div>`).join(''):'<div class="empty">Your team starts here.<br>Select a member to assign their first permissions.</div>'}</div></div>`;}
function staffEditor(){if(!state.member)return '<div class="empty">Choose a member to get started.</div>';return `<div class="notice">Editing <b>${esc(state.member.name)}</b> · ${esc(state.member.id)}</div><div class="permission-grid">${Object.entries(state.meta.permissions).map(([id,label])=>`<button class="${state.grants.has(id)?'selected':''}" data-action="grant" data-id="${id}" aria-pressed="${state.grants.has(id)}">${esc(label)}</button>`).join('')}</div><button class="primary" data-action="save-staff" ${state.meta.admin?'':'disabled'}>Done · Save staff member</button><div class="hint">Saves permissions and assigns the configured staff role immediately.</div>`;}
function ticketPage(){return `${head('Good support starts here.','One panel. Multiple categories. A private space for every conversation.')}<div class="grid2"><div class="card"><h2>Ticket settings</h2><p>Set the basics for new private ticket channels.</p>${toggle('Enable the ticket system','ticket.enabled')}${channelField('Default ticket category','ticket.category_id',true)}${channelField('Transcript log channel','ticket.log_channel_id')}${field('Open tickets per member','ticket.max_open','number')}${roleField('Support roles','ticket.support_role_ids',true)}<div class="hint">Support roles can manage every ticket. Individual staff can receive Ticket access or Manage tickets. Administrator access follows Discord’s normal rules.</div></div><div><div class="card"><h2>Ticket workflow</h2><p>Persistent buttons stay active after a restart.</p><div class="notice"><b>Open → Claim → Close → Archive</b><br>Members choose a category and submit a subject and details. Staff can claim the conversation, export a transcript, close it, reopen it, or delete a closed channel.</div><div class="hint">Add or remove participants with <code>${esc(state.config.prefix)}ticket add @member</code> and <code>${esc(state.config.prefix)}ticket remove @member</code>.</div></div><div class="card"><h2>Publish a panel</h2><p>Save your panel below, then send it to a channel.</p><label class="field"><span>Panel</span><select id="publish-panel"><option value="">Choose panel…</option>${state.config.ticket.panels.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join('')}</select></label><label class="field"><span>Destination</span>${channelSelect('publish-channel')}</label><button class="primary" data-action="publish-panel">Publish ticket panel ↗</button><div class="hint">Each publish creates a new message. Existing panels keep their published categories.</div></div></div></div><div class="card"><div class="card-head"><div><h2>Combined panels</h2><p>Group up to 25 ticket categories in a dropdown or button panel.</p></div><button data-action="add-panel">＋ Add panel</button></div>${state.config.ticket.panels.map((p,i)=>panelEditor(p,i)).join('')||'<div class="empty">Create your first panel to give members a place to ask for help.</div>'}</div><div class="card"><div class="card-head"><div><h2>Recent tickets</h2><p>Latest 100 tickets in this server.</p></div><button class="small" data-action="refresh">Refresh</button></div>${ticketTable()}</div>`;}
function panelEditor(p,i){const root=`ticket.panels.${i}`;return `<div class="row-card"><div class="card-head"><div><h3>${esc(p.title||'New ticket panel')}</h3><span class="hint">Panel ID: ${esc(p.id)}</span></div><button class="small danger" data-action="remove-panel" data-id="${i}">Remove panel</button></div><div class="form-row">${field('Title',root+'.title')}${selectField('Display as',root+'.style',[{id:'dropdown',name:'Dropdown menu'},{id:'buttons',name:'Buttons'}])}</div>${field('Description',root+'.description','textarea')}<h3>Ticket categories</h3>${p.options.map((o,j)=>{const path=root+`.options.${j}`;return `<div class="panel-option">${field('Label',path+'.label')}${field('Short description',path+'.description')}${channelField('Category override',path+'.category_id',true)}<button class="small danger" aria-label="Remove category" data-action="remove-option" data-panel="${i}" data-id="${j}">×</button></div>`;}).join('')}<div class="actions section-title"><button class="small" data-action="add-option" data-id="${i}">＋ Add category</button><span class="hint">${p.options.length}/25 · An empty override uses the default category.</span></div></div>`;}
function ticketTable(){return state.tickets.length?`<div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Member</th><th>Category</th><th>Status</th><th>Claimed by</th><th>Transcript</th></tr></thead><tbody>${state.tickets.map(t=>`<tr><td>#${t.id}</td><td>${esc(t.owner_id)}</td><td>${esc(t.option_id)}</td><td>${badge(t.status==='open',t.status,t.status)}</td><td>${esc(t.claimed_by||'Unassigned')}</td><td>${t.closed_at?`<a href="${base()}/transcripts/${t.id}">Download ↓</a>`:'Use ticket controls'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No tickets yet. Publish a panel to get started.</div>';}
function reactionsPage(){return `${head('Reaction roles','Assign roles when members react to a message.')}<div class="card"><div class="card-head"><div><h2>Reaction role mappings</h2><p>Add an emoji and role. Use an existing message ID, or leave it empty to publish a new panel.</p></div><button data-action="add-reaction">＋ Add mapping</button></div>${state.config.reaction_roles.map((r,i)=>`<div class="reaction-row">${field('Emoji',`reaction_roles.${i}.emoji`)}${roleField('Role',`reaction_roles.${i}.role_id`)}${channelField('Channel',`reaction_roles.${i}.channel_id`)}${field('Message ID (optional)',`reaction_roles.${i}.message_id`)}<button class="small danger" aria-label="Remove mapping" data-action="remove-reaction" data-id="${i}">×</button></div>`).join('')||'<div class="empty">No role mappings yet. Add your first emoji and role above.</div>'}<div class="hint">Unicode emoji or Discord custom emoji such as <code>&lt;:leaf:123456789&gt;</code>. Removing a reaction removes the role. The bot role must be above every assigned role.</div></div><div class="grid2"><div class="card"><h2>Create a role panel</h2><p>Publish all saved mappings without a message ID in the selected channel.</p><label class="field"><span>Channel</span>${channelSelect('reaction-channel')}</label><button class="primary" data-action="publish-reactions">Publish reaction panel ↗</button><div class="hint">Up to 20 emoji per message. Save before publishing.</div></div><div class="card"><h2>Using existing messages?</h2><p>Copy each message ID into its mapping, save, then add the configured reactions to those messages.</p><button data-action="seed-reactions">Add reactions to saved messages</button><div class="notice">Staff, moderation, and administrative roles cannot be self-assigned. Removing a mapping stops automation; it does not remove roles from existing members.</div></div></div>`;}
function auditPage(){return `${head('Activity log','A server-specific record of staff updates, moderation, and ticket activity.')}<div class="card">${state.events.length?`<div class="table-wrap"><table><thead><tr><th>When</th><th>Action</th><th>Actor</th><th>Details</th></tr></thead><tbody>${state.events.map(e=>`<tr><td>${esc(new Date(e.created_at).toLocaleString())}</td><td><span class="pill">${esc(e.action)}</span></td><td>${esc(e.actor_id)}</td><td>${esc(e.detail)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No activity yet. Changes made through FortuneManager will appear here.</div>'}</div>`;}
async function save(){const data=await api(base()+'/config','PUT',{config:state.config,version:state.version});state.config=data.config;state.version=data.version;state.dirty=false;rerender();toast(data.warnings?.length?data.warnings.join(' '):'Server settings saved.',!!data.warnings?.length);}
function requireSaved(){if(state.dirty)throw new Error('Save your settings before sending or publishing.');}
function rerender(){document.getElementById('content').innerHTML=renderPage();renderPreview();updateDirty();}
async function action(name,button){
 if(name==='guild')return openGuild(button.dataset.id);
 if(name==='logout'){if(state.dirty&&!confirm('Discard unsaved changes and sign out?'))return;await api('/auth/logout','POST',{});state.me=null;state.dirty=false;renderLogin();return;}
 if(name==='tab'){if(state.moduleDirty&&!confirm('Discard unsaved module settings?'))return;const previous=state.tab;state.tab=button.dataset.id;try{await loadTab();state.moduleDirty=false;renderShell();}catch(error){state.tab=previous;throw error;}return;}
 if(name==='save'){if(state.tab==='security')return saveSecurity();if(state.tab==='automod')return saveAutomod();await save();return;}
 if(name==='reset'){if(!confirm('Discard all unsaved settings?'))return;if(state.moduleDirty){state.moduleDirty=false;await loadTab();rerender();return;}const d=await api(base()+'/config');state.config=d.config;state.version=d.version;state.dirty=false;rerender();return;}
 if(name==='refresh'){if(state.moduleDirty&&!confirm('Discard unsaved module settings?'))return;state.moduleDirty=false;await loadTab();rerender();return;}
 if(name==='greet-test'){requireSaved();await api(base()+'/greet/test','POST',{});toast('Test welcome sent to your configured channel.');return;}
 if(name==='find-member'){const q=document.getElementById('member-search').value.trim();const d=await api(base()+'/members?q='+encodeURIComponent(q));document.getElementById('member-results').innerHTML=d.members.map(m=>`<button class="small" data-action="select-member" data-id="${m.id}" data-name="${esc(m.name)}">${esc(m.name)} · ${m.id}</button>`).join('')||'<div class="hint">No member found. Try their exact Discord user ID.</div>';return;}
 if(name==='select-member'||name==='edit-staff'){const s=state.staff.find(s=>s.user_id===button.dataset.id);state.member={id:button.dataset.id,name:s?.name||button.dataset.name};state.grants=new Set(s?.permissions||[]);document.getElementById('staff-editor').innerHTML=staffEditor();return;}
 if(name==='grant'){const id=button.dataset.id;if(state.grants.has(id))state.grants.delete(id);else state.grants.add(id);document.getElementById('staff-editor').innerHTML=staffEditor();return;}
 if(name==='save-staff'){requireSaved();if(!state.member)throw new Error('Choose a member.');await api(base()+`/staff/${state.member.id}`,'PUT',{permissions:[...state.grants]});await loadTab();rerender();toast('Staff permissions saved and staff role assigned.');return;}
 if(name==='remove-staff'){if(!confirm('Remove this member’s saved staff grants and assigned staff role?'))return;await api(base()+`/staff/${button.dataset.id}`,'DELETE',{});await loadTab();rerender();toast('Staff access removed.');return;}
 if(name==='add-embed-field'){if(state.config.embeds.fields.length>=25)throw new Error('Use up to 25 fields.');state.config.embeds.fields.push({name:'New field',value:'Your message',inline:false});}
 if(name==='remove-embed-field'){state.config.embeds.fields.splice(Number(button.dataset.id),1);}
 if(name==='send-embed'){requireSaved();await api(base()+'/embeds/send','POST',{});toast('Embed sent to Discord.');return;}
 if(name==='add-panel'){if(state.config.ticket.panels.length>=10)throw new Error('You can create up to 10 panels.');state.config.ticket.panels.push({id:crypto.randomUUID().slice(0,8),title:'How can we help?',description:'Choose a category to start a private conversation with our team.',style:'dropdown',options:[{id:crypto.randomUUID().slice(0,8),label:'General support',description:'Get help from the team',category_id:null}]});}
 if(name==='remove-panel'){state.config.ticket.panels.splice(Number(button.dataset.id),1);}
 if(name==='add-option'){const p=state.config.ticket.panels[Number(button.dataset.id)];if(p.options.length>=25)throw new Error('A panel can have up to 25 categories.');p.options.push({id:crypto.randomUUID().slice(0,8),label:'New category',description:'',category_id:null});}
 if(name==='remove-option'){state.config.ticket.panels[Number(button.dataset.panel)].options.splice(Number(button.dataset.id),1);}
 if(name==='publish-panel'){requireSaved();await api(base()+'/panels/publish','POST',{panel_id:document.getElementById('publish-panel').value,channel_id:document.getElementById('publish-channel').value});toast('Ticket panel published to Discord.');return;}
 if(name==='add-reaction'){if(state.config.reaction_roles.length>=100)throw new Error('Maximum 100 role mappings.');state.config.reaction_roles.push({emoji:'🌿',role_id:null,channel_id:null,message_id:null});}
 if(name==='remove-reaction'){state.config.reaction_roles.splice(Number(button.dataset.id),1);}
 if(name==='publish-reactions'){requireSaved();const d=await api(base()+'/reactions/publish','POST',{channel_id:document.getElementById('reaction-channel').value});state.config=d.config;state.version=d.version;rerender();toast('Reaction panel published. Message IDs have been saved.');return;}
 if(name==='seed-reactions'){requireSaved();const d=await api(base()+'/reactions/seed','POST',{});toast(`Added ${d.count} configured reactions.`);return;}
 if(['add-embed-field','remove-embed-field','add-panel','remove-panel','add-option','remove-option','add-reaction','remove-reaction'].includes(name)){state.dirty=true;rerender();}
}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button||state.busy)return;state.busy=true;button.disabled=true;try{await action(button.dataset.action,button);}catch(error){toast(error.message,true);}finally{state.busy=false;if(button.isConnected)button.disabled=false;}});
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.sec){state.moduleDirty=true;updateDirty();return;}if(!el.dataset.path)return;let value;if(el.type==='checkbox')value=el.checked;else if(el.multiple)value=Array.from(el.selectedOptions,o=>o.value);else if(el.type==='number')value=Number(el.value);else value=el.value;if(!value&&/(_id|message_id)$/.test(el.dataset.path))value=null;pathSet(el.dataset.path,value);if(el.dataset.path.startsWith('greet.')||el.dataset.path.startsWith('embeds.'))renderPreview();});
document.addEventListener('change',async event=>{if(event.target.id==='guild-switch'){try{await openGuild(event.target.value);}catch(error){toast(error.message,true);}if(state.guild)event.target.value=state.guild.id;}});
window.addEventListener('beforeunload',event=>{if(state.dirty||state.moduleDirty){event.preventDefault();event.returnValue='';}});
(async()=>{try{state.me=await api('/api/me');const d=await api('/api/guilds');state.guilds=d.guilds;state.invite=d.invite;renderGuilds();}catch(error){if(!state.me)renderLogin();else{app.innerHTML='<div class="loading"><p>Could not load your servers.</p><a class="button" href="/">Try again</a></div>';toast(error.message,true);}}})();
function secInput(key,label,value,type='number'){return `<label class="field"><span>${label}</span><input data-sec="${key}" type="${type}" value="${esc(value??'')}" ${type==='checkbox'&&value?'checked':''}></label>`;}
function secChoice(key,label,value,choices){return `<label class="field"><span>${label}</span><select data-sec="${key}">${choices.map(c=>`<option value="${c}" ${c===value?'selected':''}>${c}</option>`).join('')}</select></label>`;}
function securityPage(){const d=state.security,p=d.policy;return `${head('Antinuke','Only the server owner can change these settings.')}<div class="card"><div class="grid3">${secInput('enabled','Enabled',p.enabled,'checkbox')}${secChoice('mode','Mode',p.mode,['observe','enforce'])}${secChoice('punishment','Containment',p.punishment,['strip','ban','kick'])}${secInput('actor_score','Member score / 60s',p.actor_score)}${secInput('guild_score','Server score / 60s',p.guild_score)}${secInput('auto_lockdown','Automatic lockdown',p.auto_lockdown,'checkbox')}${secInput('log_channel_id','Log channel ID',p.log_channel_id,'text')}</div><p>Strip removes manageable roles. If dangerous permissions remain, the bot attempts a ban. Lockdown removes dangerous permissions from manageable staff roles.</p><label class="field"><span>Single-use confirmation code</span><input id="security-code" type="password" autocomplete="off" placeholder="Run antinuke dashboard in Discord"></label><div class="table-wrap"><table><thead><tr><th>Rule</th><th>Enabled</th><th>Actions</th><th>Seconds</th><th>Hourly limit</th></tr></thead><tbody>${Object.entries(p.rules).map(([name,r])=>`<tr><td>${esc(name)}</td><td>${secInput('rules.'+name+'.enabled','',r.enabled,'checkbox')}</td>${['count','seconds','hourly'].map(k=>`<td>${secInput('rules.'+name+'.'+k,'',r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div><div class="card"><h2>Health</h2><p>Missing permissions: ${esc(d.health.missing_permissions.join(', ')||'None')}<br>Roles above the bot: ${esc(d.health.unmanageable_roles.join(', ')||'None')}<br>Workers: ${d.health.workers_running?'Running':'Needs attention'}</p></div><div class="card"><h2>Recent incidents</h2><div class="table-wrap"><table><tr><th>Case</th><th>Member</th><th>Rule</th><th>Status</th><th>Reason</th></tr>${d.incidents.map(i=>`<tr><td>${i.id}</td><td>${esc(i.actor_id)}</td><td>${esc(i.rule)}</td><td>${esc(i.status)}</td><td>${esc(i.reason)}</td></tr>`).join('')}</table></div></div><div class="card"><h2>Recovery and containment jobs</h2>${d.jobs.map(j=>`<p>#${j.id} · ${esc(j.kind)} · ${esc(j.status)}<br>${esc(j.error)}</p>`).join('')||'<p>No jobs.</p>'}</div>`;}
function automodPage(){const p=state.automod.config;return `${head('Automod','Repeated-text detection, content filters, and instant-ban words.')}<div class="card"><div class="grid3">${secInput('enabled','Enabled',p.enabled,'checkbox')}${secChoice('mode','Mode',p.mode,['observe','enforce'])}${secInput('log_channel_id','Log channel ID',p.log_channel_id,'text')}${['timeout_seconds','spam_count','spam_seconds','duplicate_count','repeat_count','repeat_characters','mention_count','caps_percent','caps_min','emoji_count','attachment_count','escalate_after'].map(k=>secInput(k,k.replaceAll('_',' '),p[k])).join('')}</div><div class="table-wrap"><table><tr><th>Rule</th><th>Enabled</th><th>Action</th></tr>${Object.entries(p.rules).map(([n,r])=>`<tr><td>${esc(n)}</td><td>${secInput('rules.'+n+'.enabled','',r.enabled,'checkbox')}</td><td>${secChoice('rules.'+n+'.action','',r.action,['delete','warn','timeout','kick','ban'])}</td></tr>`).join('')}</table></div><div class="grid2">${['words','ban_words','allowed_domains','blocked_domains','blocked_extensions','ignored_channels','ignored_roles'].map(k=>`<label class="field"><span>${esc(k.replaceAll('_',' '))} (one per line)</span><textarea data-sec="${k}" data-list="true">${esc(p[k].join('\n'))}</textarea></label>`).join('')}</div><p>Ban words delete the message and ban its author in enforce mode. They apply despite ordinary role/channel exemptions. Adding them here also requires Ban Members.</p><h2>Join-burst guard</h2><div class="grid3">${secInput('raid.enabled','Enabled',p.raid.enabled,'checkbox')}${secInput('raid.count','Join count',p.raid.count)}${secInput('raid.seconds','Window in seconds',p.raid.seconds)}${secInput('raid.min_age_hours','Minimum account age in hours',p.raid.min_age_hours)}</div><p>Native Discord rules are managed separately with <code>automod native on</code> and <code>automod native off</code>.</p></div>`;}
function collectSecurity(original){const out=structuredClone(original);document.querySelectorAll('[data-sec]').forEach(el=>{const keys=el.dataset.sec.split('.'),key=keys.pop(),obj=keys.reduce((o,k)=>o[k],out);obj[key]=el.dataset.list?el.value.split('\n').map(x=>x.trim()).filter(Boolean):el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(key==='log_channel_id'&&!obj[key])obj[key]=null;});return out;}
async function saveSecurity(){const d=await api(base()+'/security','PUT',{policy:collectSecurity(state.security.policy),version:state.security.version,code:document.getElementById('security-code').value.trim()});state.security.policy=d.policy;state.security.version=d.version;state.moduleDirty=false;await loadTab();rerender();toast('Security settings saved.');}
async function saveAutomod(){state.automod=await api(base()+'/automod','PUT',{config:collectSecurity(state.automod.config),version:state.automod.version});state.moduleDirty=false;rerender();toast('Automod settings saved.');}
